import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/nav";
import { FormProvider } from "@/context/FormContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey="pk_test_bGlnaHQtbWF5Zmx5LTQwLmNsZXJrLmFjY291bnRzLmRldiQ">
      <html lang="en">
        <body className={inter.className}>
          <FormProvider>
            <Navbar />
            {children}
          </FormProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
